DELETE FROM ADMINISTRATEUR
DELETE FROM CONDUCTEUR
DELETE FROM MECANICIEN
DELETE FROM NAVETTE
DELETE FROM OPERATION
DELETE FROM QUAI
DELETE FROM RESERVATION
DELETE FROM REVISION
DELETE FROM STATION
DELETE FROM TRANSFERT
DELETE FROM USAGER
DELETE FROM VOYAGE
INSERT INTO ADMINISTRATEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (1 , CURRENT_TIMESTAMP, 'admin', 'admin', 'Lucas', 'UZAN')
INSERT INTO ADMINISTRATEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (2 , CURRENT_TIMESTAMP, 'admin', 'admin', 'Mahdi', 'HENTATI')
INSERT INTO ADMINISTRATEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (3 , CURRENT_TIMESTAMP, 'admin', 'admin', 'Philippe', 'ROQUES-GEOFFROY')
INSERT INTO CONDUCTEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (1 , CURRENT_TIMESTAMP, 'conduc', 'conduc', 'Lucas', 'UZAN')
INSERT INTO CONDUCTEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (2 , CURRENT_TIMESTAMP, 'conduc', 'conduc', 'Mahdi', 'HENTATI')
INSERT INTO CONDUCTEUR (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (3 , CURRENT_TIMESTAMP, 'conduc', 'conduc', 'Philippe', 'ROQUES-GEOFFROY')
INSERT INTO MECANICIEN (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (1 , CURRENT_TIMESTAMP, 'mecano', 'mecano', 'Lucas', 'UZAN')
INSERT INTO MECANICIEN (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (2 , CURRENT_TIMESTAMP, 'mecano', 'mecano', 'Mahdi', 'HENTATI')
INSERT INTO MECANICIEN (ID, DATE_CREATION, LOGIN, MOT_DE_PASSE, NOM, PRENOM) VALUES (3 , CURRENT_TIMESTAMP, 'mecano', 'mecano', 'Philippe', 'ROQUES-GEOFFROY')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (1 ,'sol.d', 'Terre', 15, 'Disponible')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (2 ,'pegasi.b', 'Dimidium', 15, 'Disponible')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (3 ,'delphini.b', 'Arion', 15, 'Disponible')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (4 ,'cancri.c', 'Brahe', 15, 'Disponible')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (5 ,'epsilonTauri.b', 'Amateru', 15, 'Disponible')
INSERT INTO STATION (ID, LOCALISATION, NOM, NOMBRE_QUAIS, STATUT) VALUES (6 ,'gammaCepheiA.b', 'Tadmor', 15, 'Disponible')